appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: gL4eY6TAmxH3SjUWrsmvtKLOEIG4y/LZTrQzHiJ/FLL5PzG3jMAHXm/ojLNPcrjczradJvqMlxGGoeYeSrku+cz+GtD2orf7CETxFNdzp2sslQ64r+0Dao8FzVQ+gd7qjTaxj0uDhJ2kna43gHWva0HXIoPBbdT1vwDPJLhVyfKt0byz54bHL7DDXhCCDdu8ZpbD/VMOGVKiwtPC2bftsFcyvduszKECQ5OZQf4iO0KWX72ET3Pu7uZkj52WchFOA87CEhRoEAwrl+j+sNBf4lqivpvXQTAybibAfpA9d1xMKiZ/J/NDGFSTTeDVuEiRsZhYBCVeDb2TkudTDNn1Zj2+2sgSLuMU4fvxhi3VanpCZD4FbGZ4oAeiacsap8YZ6eUAu1LKMsxRDL5r0wQzsYIMthBfImtbQPct0uvP1tCkVQ5yDm1dpx6RY7tGPvvGLt4Cy0wzR9u+82bKAmLmNPrjqSc+pLtp7cFjNFLg3p73UiPKi/eiQmP7uT3LzXugkh9uU5r8lKv721HqjD/s2cKf8BWPd4r0iQcFK4MVjrgEUA37ILLjkdA7Si5/Ssfn7TCujdplFv+5WhfO9vxxXiUJCrxinEZ0h+Qy5vyMdH1+50w5iCUzhCp5Ssg/VgV5AGBHeLLBMjiTYRuaPy0eo18f93ZpgnIOiFtCpX4oL9k=
